openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for Arnz
paths:
    /:
        delete:
            tags:
                - Arnz
            summary: delete Arnz
            operationId: Arnz#delete
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Temporibus nostrum modi fugit praesentium aut aliquam.
        get:
            tags:
                - Arnz
            summary: read Arnz
            operationId: Arnz#read
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Est nam aut dolor id praesentium.
        post:
            tags:
                - Arnz
            summary: create Arnz
            operationId: Arnz#create
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Atque fugit vero quo aut cupiditate.
        put:
            tags:
                - Arnz
            summary: update Arnz
            operationId: Arnz#update
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Voluptas fuga.
    /caller:
        get:
            tags:
                - Arnz
            summary: caller Arnz
            operationId: Arnz#caller
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IntrospectResponse'
                            example:
                                caller: Repellendus vitae non.
    /health:
        get:
            tags:
                - Arnz
            summary: health Arnz
            operationId: Arnz#health
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResponseBody'
                            example:
                                action: Voluptates voluptate quis est nobis.
components:
    schemas:
        IntrospectResponse:
            type: object
            properties:
                caller:
                    type: string
                    example: Beatae nulla qui aut.
            example:
                caller: Labore mollitia nihil architecto et.
            required:
                - caller
        ResponseBody:
            type: object
            properties:
                action:
                    type: string
                    example: Quos hic dolorum quisquam aliquid.
            example:
                action: Minus itaque hic at autem est.
            required:
                - action
tags:
    - name: Arnz
